### PR TITLE
Hide elements

### PR DESCRIPTION
**Pull request by koppen37**
@sduduzog The issue you mentioned in #91 only happened during the animation right? Afterwards all the 7 apps were visible?

I put the second list of apps to the bottom of the first list in the constraintlayout, while originally this was stuck to the bottom of parent. I have now updated this to parent again (see 4f6088d ) , can you check that it now behaves as expected? The animation might still be changed a bit, but should be closer to the original one. 

PS. I won't be near a pc for the next week, so any updates from my side will have to wait until then.

### CODE REVIEW

**Comment by sduduzog** [comment]
Correct, it was just the animation. I'll check this out

**Comment by koppen37** [comment]
Just noticed that the default values might be a bit off at the moment:

- Call/Camera icon are disabled
- Clock doesn't function as shortcut while the calendar does

Let me know if you want any of the default values changed.

**Comment by sduduzog** [comment]
yea, might be alarming for unaware users of the config, @koppen37 Might be a good idea to have them enabled by default

**Comment by sduduzog** [comment]
Almost... almost there 😅 but the cut is still visible

image

Here's also the emulator config
image

**Comment by koppen37** [comment]
I tried to be clever by only setting  the constraint values that changed, but clearly this always resulted in some strange differences. I now stopped trying it be clever and just copied all the original constraint values, this should make the animation identical to before.

Unfortunately my pc (only 4GB ram) is already struggling with Android Studio so can't run an emulator next to it to test it on other devices.  However on my test device (Nexus 5X) the animation and layouts now indeed look identical to before.

**Comment by sduduzog** [comment]
It's amazing what you've done on a 4GB ram machine...Mine is 8GB and it's almost at a tipping point in every application I open

**Pull request closed without merging**
