### PR TITLE
Hide elements on homescreen

### PR DESCRIPTION
**Pull request by koppen37**
Hi @sduduzog , 

I thought it might be convenient to already open the pull-request for the hide_elements branch as discussed in #84. If there are any changes you would prefer don't hesitate to let me know.

The last two commits should hopefully make it easier to set default values for the different elements on the homescreen, as a showcase it now disables the call/camera icons and time/date shortcuts by default

### CODE REVIEW

**Comment by koppen37** [comment]
As you can see, I'm struggling a bit with the best way to store the different setting values (and their default values). Right now I still use the same method as the current implementation, but I think that a switch to PreferenceScreen might be a good idea. I'm currently experimenting with it in [this](https://github.com/koppen37/slim-launcher/tree/hide_elements_preferencescreen) branch, which has a very very very WIP implementation at the moment. Should hopefully be fully functional in the next few days. 

Curious whether you have a strong preference for either one of the implementations.

**Comment by koppen37** [comment]
The other branch now also contains a fully functional (and themed) settings page, using PreferenceScreen. The advantage is that we can now set the default values in the xml, so we don't need to keep track of them inside the code. However UI-wise it is a bit trickier to make it blend in. I will leave the two branches (this and [preferencescreen](https://github.com/koppen37/slim-launcher/tree/hide_elements_preferencescreen)) as they are now until you had time to take a look. 

Screenshots of the current implementations:

### This pull-request


### PreferenceScreen - custom CheckboxPreference

- Edited the layout of the title and items in the preference screen to closely match the original settings screen
- Edited the layout of CheckboxPreference such that the checkbox is removed and the summary text is at the end of the line. This way the summaryOn en summaryOff properties are used to switch between the states. Not tested for robustness yet (long text etc). 

 

### PreferenceScreen - default SwitchPreferences
Same branch as above, but use the default SwitchPreference instead of the custom CheckboxPreference

**Comment by sduduzog** [comment]
Judging from screenshots, I'd say, please add some padding around the layouts so that the content doesn't start at the edge of the screen.

I like the native switches as they look more relatable... Although the text aesthetic is tempting, it seems a bit off in this case and I don't know why.

Also the subtitles, date and time, align them to the side also, but make them bold or and some opacity a bit to them, overall this looks cool.


I made so many changes to master, I hope it doesn't break much of your PR.
Make sure you keep the deleted files deleted, especially the ones around dependency injection.

**Comment by koppen37** [comment]
Will take a look at the conflicts (together with your preferences) later tonight/ tomorrow. Will let you know when everything is ready.

**Comment by koppen37** [comment]
This PR should now be up to date again. The branch has now switched to the `SwitchPreference`, added some padding, a summary for the shortcuts and fixed some small things in the transition. Still struggling a bit with the `PreferenceCategory` layout, for now went back to the default layout and added a divider. Let me know if you want me to change/add anything. 

Current state:
Screenshot_20200908-220342_Slim_Launcher

**Comment by koppen37** [comment]
Sorry for the spam, small update: made the subtitles bold and changed all the context!! to requireContext().

Now looks like:
Screenshot_20200908-223916_Slim_Launcher

**Comment by sduduzog** [comment]
Testing this after merge on emulator... When you have all 7 apps added sliding up and down you'll notice that they get cut off by some invisible overlap at the bottom of the screen, reverting in the meantime @koppen37

**Pull request merged**
