### PR TITLE
Improves Code Quality

### PR DESCRIPTION
**Pull request by subbramanil**
- Applies some minor code quality improvements.
- Improvements suggested by [Codacy](https://www.codacy.com). It uses the below code quality tools to suggest improvements. 
  - Checkstyle 8.13
  - Detekt 1.0.0.RC8
  - PMD 6.4.0
  - PMD (Legacy) 5.8.1
  - RemarkLint 6.0.2

**Note**: 

- This PR is to show the possible tools that you can use to improve code quality.
- Codacy has a couple of free plans that could work out well for your usage.
- Please merge the previous PRs before merging this one to see the changes only included in this PR.

### CODE REVIEW

**Comment by sduduzog** [comment]
I didn't notice the merge conflict with the build.gradle file

**Comment by subbramanil** [comment]
Yeah. I thought if you merged the PRs in order, You would not run into this issue.

**Comment by subbramanil** [comment]
It should be good now.

**Comment by sduduzog** [comment]
Quick question... Should I be also making pull request for code changes? I'm asking this because I just made a few edits on the merged commits and I'm not sure how it reflects on your side.

**Comment by subbramanil** [comment]
Can you submit Pull Request? Yes. 

Should you need to do? No. I can pull in your changes when needed. 

Typically, the way it works in Github is there's an original repository; there are forked repositories. Whenever anyone contributes, PRs are submitted from forked repositories to the original repository. And it's the owner of the forked repositories who needs to pull the changes from original repositories if needed. 

In any case, there's no rule for the forked repositories to match the original repository. The forked repository is a copy of the original repository which another person owns. He/She may contribute to the original repository or maintain the forked repository as his/her own. But he does need to follow the license agreements in the repository.

**Pull request merged**
